### ISSUE TITLE
The flight times for tickets are represented with a UTC (GMT + 1) format instead of the user's locale

### ISSUE THREAD

**Issue by deankevorkian** [guymalul95/BetterFly#1]
Hi,
First of all great work! The experience is incredible and the performance is absolutely amazing. I'm satisfied I can use the same software on both my iPhone™ and Android(c) simultaneously and have the same experience and performance!
One thing that has been bugging me, though, is that the times displayed for the flights are not presented in the correct format for the user (using his time locale settings). Therefore I am required to convert the dates / times from the UTC format to my own format (GMT + 2).

OS: Windows 10
Version: Latest (0.0.1)

Thank you!

**Comment by guymalul95** [comment]
דין לך מפה יזבל

**Comment by deankevorkian** [comment]
What does this mean? Can I help, in any way, with the issue?
